### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by RotDan196** [therealmarius/Spotify-2-AppleMusic#25]
PS C:\Users\danie\Desktop\Spotify-2-AppleMusic-1.3.2\Spotify-2-AppleMusic-1.3.2> python3 convertsongs.py trap.csv
Traceback (most recent call last):
  File "C:\Users\danie\Desktop\Spotify-2-AppleMusic-1.3.2\Spotify-2-AppleMusic-1.3.2\convertsongs.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PS C:\Users\danie\Desktop\Spotify-2-AppleMusic-1.3.2\Spotify-2-AppleMusic-1.3.2>

what i have to do now?

**Comment by therealmarius** [comment]
Hey! Thanks for reaching out.

Try running this command to install the requests module and then try again.

`pip install requests`

Best,
therealmarius

**Comment by RotDan196** [comment]
OK! I solved, the main problem was that i was typing "python3 convertsongs.py filename.csv" as the readme file says, but i've tried by typing "py convertsongs.py filename.csv" and it worked.
