### ISSUE TITLE
Error 403 while creating playlist

### ISSUE THREAD

**Issue by limefps** [therealmarius/Spotify-2-AppleMusic#33]
Hiya, 
getting error 403 when it tries to create a playlist. 
Here's the full error Traceback:

> Enter the country code (e.g., FR, PL, US etc.): DE
> Traceback (most recent call last):
>   File "C:\Users\akerr\Downloads\Spotify-2-AppleMusic-master\Spotify-2-AppleMusic-master\convertsongs.py", line 239, in <module>
>     create_playlist_and_add_song(os.path.join(argv[1], file))
>   File "C:\Users\akerr\Downloads\Spotify-2-AppleMusic-master\Spotify-2-AppleMusic-master\convertsongs.py", line 181, in create_playlist_and_add_song
>     playlist_identifier = create_apple_music_playlist(s, playlist_name)
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\akerr\Downloads\Spotify-2-AppleMusic-master\Spotify-2-AppleMusic-master\convertsongs.py", line 44, in create_apple_music_playlist
>     raise Exception(f"Error {response.status_code} while creating playlist {playlist_name}!")
> Exception: Error 403 while creating playlist aa  we do a little music!

I think this may be due to the "your cookies" section of the readme? To me it isn't entirely clear what exactly is meant by "your cookies", since the media-user-token is part of the "Cookie" section of the response header. Mine looks like:

> dssid2=REDACTED; dssf=1; geo=DE; dslang=US-EN; site=USA; wosid-replay=REDACTED; myacinfo=REDACTED; commerce-authorization-token=REDACTED; itspod=70; media-user-token=REDACTED; itua=DE; pldfltcid=REDACTED; pltvcid=REDACTED; media-user-token=REDACTED

I just pasted the whole cookie section in. Could also be media-user-token, I pasted the whole thing including the 'media-user-token=' for that. As for the Bearer (pretty sure it isn't this), I pasted the whole thing including the 'Bearer '.

**Comment by limefps** [comment]
The problem was caused by the 'media-user-token='. Dropping it made it work perfectly.
I'd recommend the clarifications to the readme along the following lines:

1. For Authorization, make sure to copy the 'Bearer ' part.
2. For media-user-token, only copy what follows the =, so from "media-user-token=mytokenhere", only copy mytokenhere. media-user-token is a subcomponent of the 'Cookie' element
3. For Cookies, copy the full 'Cookie' element of the header

Thanks for the great tool!
Closing the issue, although I don't "really" consider it fixed pending clarifications in the readme.

**Comment by limefps** [comment]
The problem was caused by the 'media-user-token='. Dropping it made it work perfectly.
I'd recommend the clarifications to the readme along the following lines:

1. For Authorization, make sure to copy the 'Bearer ' part.
2. For media-user-token, only copy what follows the =, so from "media-user-token=mytokenhere", only copy mytokenhere. media-user-token is a subcomponent of the 'Cookie' element
3. For Cookies, copy the full 'Cookie' element of the header

Thanks for the great tool!
Closing the issue, although I don't "really" consider it fixed pending clarifications in the readme.

**Comment by therealmarius** [comment]
Hey!

Nice that you could resolve your problem by yourself. I don't know what kind of interface you have, but on my end, I have the media-user-token that has its own header/component. Even though, it also appears in the Cookies header, as subcomponent.
My guess is that you wasn't inspecting the right request call.

I'll take notes of the recommendations you made.

Best,
therealmarius

**Comment by limefps** [comment]
Yep, turns out I was indeed on the "wrong" request. Everything required is there on either of the two, except the media-user-token as its own element, is available for both of the requests. I had assumed by "second request" you meant the one that occurred later chronologically (by about 400ms), and that turns out to have been incorrect.

I guess the devtools you were using sort chronologically by recent first? Not sure if this is default behaviour, mine, in Firefox, are sorted by oldest first so the "newer" request was the 2nd one. I also just checked Chromium, and that behaves the same as Firefox, i.e. older requests are higher up, meaning the newer request (which in my case was missing the media-user-token header element), is the "second request".
