### ISSUE TITLE
Error on run - invalid literal for int() with base 10

### ISSUE THREAD

**Issue by emmjayvee** [therealmarius/Spotify-2-AppleMusic#7]
I am hitting this error when running. Do I need to modify the csv that was exported perhaps?

```
Traceback (most recent call last):
  File "/Users/xxxxxxxxxx/Downloads/Spotify-2-AppleMusic-master/addsongs.py", line 43, in <module>
    itunes_identifier = int(line)
ValueError: invalid literal for int() with base 10: '"Track URI","Track Name","Artist URI(s)","Artist Name(s)","Album URI","Album Name","Album Artist URI(s)","Album Artist Name(s)","Album Release Date","Album Image URL","Disc Number","Track Number","Tr
```

A second issue I had was my terminal only allows 1024 characters to be pasted in. I hardcoded the cookies in the file to overcome this. Might be worth mentioning for other users in the docs?

Thanks!

**Comment by therealmarius** [comment]
Hi, thanks for reaching out!
1. I never faced the 1024 character limit on my terminal, but you are right I'll add it to the docs.
2. No you don't need to edit the .csv file at all. Because we're using [Exportify](https://watsonbox.github.io/exportify/) to get our base .csv, I need to check if they have made any changes to the file structure.
I'll keep you posted.

**Comment by therealmarius** [comment]
Hey, I understood what's happening.

When you run `python3 addsongs.py yourfile.csv` you passed as input the wrong file.
You need to pass as input the converted .csv file. You get this file by running this command: 
`python3 getitunesid.py filefromexportify.csv`
And then you can run this command to upload your converted IDs of song to your Apple Music:
`python3 addsongs.py fileconverted.csv`

_Please note that `yourfile.csv`, `filefromexportify.csv`, `fileconverted.csv` are example of filenames. Please use your correct filenames._

Thanks.

**Comment by therealmarius** [comment]
I updated the README.md file with the fix for the paste character limit.
Thanks and enjoy your converted playlists!
